# Generated by Django 3.2 on 2021-09-23 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.site'),
            preserve_default=False,
        ),
    ]
