# Generated by Django 3.2 on 2021-09-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_profile_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.site'),
        ),
    ]
