# Generated by Django 3.2 on 2021-09-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_profile_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.site'),
            preserve_default=False,
        ),
    ]
